# Generated by Django 6.0.6 on 2026-06-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='loyalty_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
