# Generated by Django 6.0.5 on 2026-06-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_status_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
