# Generated by Django 6.0.5 on 2026-06-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delivery_delivery_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
