# Generated by Django 6.0.6 on 2026-06-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('is_approved', models.BooleanField(default=False)),
                ('commission_rate', models.FloatField(default=10.0)),
                ('bank_account', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=11)),
            ],
        ),
    ]
