# Generated by Django 6.0.6 on 2026-06-19 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_status_delivery'),
        ('returns', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='order',
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DELIVERY_AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PICKUP_ASSIGNED', 'Pickup Assigned'), ('PICKED_UP', 'Picked Up'), ('RECEIVED_AT_WAREHOUSE', 'Received at Warehouse'), ('REFUNDED', 'Refunded'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=30),
        ),
    ]
