# Generated by Django 6.0.5 on 2026-06-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_remove_returnrequest_order_returnrequest_order_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_photo',
            field=models.ImageField(blank=True, null=True, upload_to='returns/pickups/'),
        ),
    ]
