# Generated by Django 6.0.5 on 2026-06-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0004_returnrequest_pickup_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='pickup_agent',
        ),
    ]
