# Generated by Django 6.0.6 on 2026-06-19 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Customer'), ('seller', 'Seller'), ('manager', 'Manager'), ('admin', 'Admin'), ('DELIVERY_AGENT', 'Delivery Agent')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_zone', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
