# Generated by Django 6.0.5 on 2026-06-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role_deliveryagentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Customer'), ('seller', 'Seller'), ('manager', 'Manager'), ('admin', 'Admin')], default='user', max_length=20),
        ),
        migrations.DeleteModel(
            name='DeliveryAgentProfile',
        ),
    ]
