# Generated by Django 6.0.5 on 2026-06-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role_delete_deliveryagentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Customer'), ('seller', 'Seller'), ('manager', 'Manager'), ('admin', 'Admin'), ('delivery_agent', 'Delivery Agent')], default='user', max_length=20),
        ),
    ]
